version: "3.9"

services:
  # Development application service
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://eventuser:eventpass@db-dev:5432/eventdb?schema=public
      - REDIS_URL=redis://redis-dev:6379
    env_file:
      - .env
    depends_on:
      - db-dev
      - redis-dev
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - eventpass-dev-network

  # Development database
  db-dev:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: eventuser
      POSTGRES_PASSWORD: eventpass
      POSTGRES_DB: eventdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    networks:
      - eventpass-dev-network

  # Development Redis
  redis-dev:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-dev-data:/data
    networks:
      - eventpass-dev-network

volumes:
  postgres-dev-data:
  redis-dev-data:

networks:
  eventpass-dev-network:
    driver: bridge
